### ISSUE TITLE
Analizar estado actual del proyecto por  áreas

### ISSUE THREAD

**Issue by jersonlopez** [calidadudea/InnovaTeam#36]
Se debe realizar un informe detallados del estado actual del proyecto según los hallazgos encontrados al realizar el seguimiento de cada area.

* [x] Desarrollo
* [x] Calidad y testing
* [x] Diseño

**Comment by SergioCastri** [comment]
[Estado actual.pdf](https://github.com/calidadudea/InnovaTeam/files/3552684/Estado.actual.pdf)
